version: "3.4"

services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./src:/var/www/html
    ports:
      - ${APP_PORT:-80}:80
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=${MYSQL_DATABASE:-db_document_table}
      - MYSQL_USER=${MYSQL_USERNAME:-user}
      - MYSQL_PASSWORD=${MYSQL_USERPASS:-password}
  phpmyadmin:
    image: phpmyadmin:latest
    volumes:
      - ./docker/phpmyadmin/sessions:/sessions
      - ./docker/phpmyadmin/phpmyadmin-misc.ini:/usr/local/etc/php/conf.d/phpmyadmin-misc.ini
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=${MYSQL_USERNAME:-user}
      - PMA_PASSWORD=${MYSQL_USERPASS:-password}
    ports:
      - 4040:80
    depends_on:
      - mysql
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver2022
    hostname: sqlserver2022
    ports:
      - 1433:1433
    volumes:
      - ./docker/mssql/data:/var/opt/mssql/data
      - ./docker/mssql/log:/var/opt/mssql/log
      - ./docker/mssql/secrets:/var/opt/mssql/sec
    environment:
      - ACCEPT_EULA=${ACCEPT_EULA:-Y}
      - TZ=${TZ:-Asia/Tokyo}
      - MSSQL_COLLATION=${MSSQL_COLLATION:-Japanese_CI_AS}
      - MSSQL_LCID=${MSSQL_LCID:-1041}
      - MSSQL_AGENT_ENABLED=${MSSQL_AGENT_ENABLED:-true}
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD:-P@ssw0rd1234}